### ISSUE TITLE
devcerts dir not coming up in .config after deleting

### ISSUE THREAD

**Issue by jeffwillette** [davewasmer/devcert#21]
I wanted to run through the whole initialization process again so I deleted `~/.config/devcert` and deleted the trusted certs from my `Keychain Access`  in the hopes that I could regenerate everything.

I found that the directory is not coming back after deleting. I went through the issues and saw there was also something in `~/Library/Application Support/devcert` so I deleted that and ran again, this dir did come back but the `/.config` dir still did not.

Any idea how to get it to come back?

**Comment by davewasmer** [comment]
@deltaskelta did you have an older version of devcert installed? If you are on macOS (which it sounds like you are), then the new location of the config directory is `~/Library/Application Support/devcert`, rather than `~/.config`. So sounds like it's acting as expected here.

A few unrelated questions:

1. Why are you manually installing `nss`? It doesn't hurt anything, but devcert will do that for you automatically by default.

2. Why the link/unlink?

Just a heads up, I'm planning on publishing `devcert-cli` shortly which I imagine would handle this whole `devcert.tmp.js` dance here (i.e. you could just `npx devcert example.com`, or something like that).
